### ISSUE TITLE
Load exchanges,queues ,binding at startup

### ISSUE THREAD

**Issue by tiryu** [thombergs/code-examples#2]
Hello, 

I tried your sample project on rabbitmq and I've got a question about initialization of configuration for rabbitmq (queues, binding, exchange).

Is there any way to create, on rabbitserver at startup of server spring boot, queues and others ?

Actually, if I don't start the project with your properties to init queues, I need to send a message to rabbit to initiate creation of Queues, bindings...

Thank you.

**Comment by thombergs** [comment]
Hi,

Spring AMQP automatically creates the configured queues, exchanges and bindings when the Spring Boot application starts. You shouldn't have to configure anything on the RabbitMQ Server. My sample application should run with a default installation of RabbitMQ (at least the Windows version).

Regards,
Tom

**Comment by tiryu** [comment]
Okay, I wanted to add something about init queues, bindings.
When you have two services spring boot, with one for subscribe and the other one for publish :
- on publish service : its created only when sendMessage is call once.
- on subscribe service : its created at startup .
