### ISSUE TITLE
Git clone doesn't work for liquibase project

### ISSUE THREAD

**Issue by oyekanmiayo** [thombergs/code-examples#27]
When I try:  `git clone https://github.com/thombergs/code-examples/spring-boot/data-migration/liquibase`,

I get this error on my terminal: `remote: Not Found
fatal: repository 'https://github.com/thombergs/code-examples/spring-boot/data-migration/liquibase/' not found`

**Comment by thombergs** [comment]
you need to clone the whole repo, i.e. `https://github.com/thombergs/code-examples`
